server:
  port: 8080
  servlet:
    context-path: "/onlineAdmain"

  tomcat:
    max-http-post-size: 100MB
spring:
  datasource:
    username: root
    password: 950405
    url: jdbc:mysql://localhost:3306/online?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force-response: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
logging:
  path: E:\
  level:
    top.musuixin.Mapper: debug

